### ISSUE TITLE
Interface improvement request: store.get.someProp instead of store.get('someProp') 

### ISSUE THREAD

**Issue by lanemt** [bcherny/babydux#1]
babydux looks interesting - but i'm not a huge fan that a string literal is used to get a value from the store. example (`store.get('someProp')`).

I would prefer to have type safety on the store and the prop getters and setters.
It would be ideal to call via a getter `store.get.someProp` or simply `store.someProp` with compile time type safety for the getters and setters.

This could be done with [ES6 Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy)

There are also some proxy polyfill options out there for backward compatibility.

**Comment by bcherny** [comment]
Hi @lanemt!

Thanks for the suggestion, but the current API is totally typesafe already. Here's an example:

```ts
type Store = {
  a: number
  b: string
}

let store = createStore<Store>({
  a: 1,
  b: 'foo'
})

store.get('a')    // number
store.set('b')(2) // Compile-time error! 2 is not a string
```

I chose this get/set syntax because it is familiar to a lot of people coming from Backbone, Angular, Ember, etc.
